CREATE TABLE `settings` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`business_name` text,
	`business_address` text,
	`business_phone` text,
	`business_tin` text,
	`receipt_header` text,
	`receipt_footer` text,
	`business_logo` text,
	`primary_color` text DEFAULT '#3b82f6',
	`tax_rate` real DEFAULT 18,
	`currency` text DEFAULT 'TZS',
	`currency_symbol` text DEFAULT 'TZS',
	`date_format` text DEFAULT 'DD/MM/YYYY',
	`receipt_number_format` text DEFAULT 'SALE-{TIMESTAMP}-{COUNTER}',
	`efd_enabled` integer DEFAULT false,
	`efd_endpoint` text,
	`efd_api_key` text,
	`efd_last_test_date` integer,
	`efd_test_status` text,
	`low_stock_threshold` integer DEFAULT 5,
	`email_notifications_enabled` integer DEFAULT false,
	`notification_email` text,
	`alert_sound_enabled` integer DEFAULT true,
	`alert_on_low_stock` integer DEFAULT true,
	`alert_on_out_of_stock` integer DEFAULT true,
	`alert_on_dead_stock` integer DEFAULT false,
	`dead_stock_days` integer DEFAULT 30,
	`print_receipt_automatically` integer DEFAULT false,
	`show_tax_on_receipt` integer DEFAULT true,
	`show_barcodes_on_receipt` integer DEFAULT false,
	`updated_by` integer,
	`created_at` integer DEFAULT (unixepoch()),
	`updated_at` integer DEFAULT (unixepoch()),
	FOREIGN KEY (`updated_by`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action
);
